### ISSUE TITLE
homework advances to the next step, then goes back to show feedback

### ISSUE THREAD

**Issue by gregfitch** [openstax/tutor#517] opened 2019-07-16 21:22 UTC
### Description
Description

https://slack-files.com/T0F5B5PGQ-FLJNFH41L-a86917a4ff

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by Brooke-Fail** [comment] 2019-09-05 16:43
This has improved but is still occurring in QA. New issue has been created and is being tracked here: https://github.com/openstax/tutor/issues/590. Moving this card to regression since it has improved and will be going out in the 9-11 release.

**Comment by Brooke-Fail** [comment] 2019-09-09 17:38
Verified in Staging.

**Comment by Brooke-Fail** [comment] 2019-09-11 17:00
Verified in Production.

**Closed by Brooke-Fail** 2019-09-11 17:00 UTC
Labels: bug, priority1-high
