### ISSUE TITLE
Threre is a 500 error when requesting a refund for a course 

### ISSUE THREAD

**Issue by Brooke-Fail** [openstax/tutor#569] opened 2019-08-23 17:55 UTC
### Description
When a student requests a refund for a course, after they click submit, a 500 error is triggered and the refund is not given. 

**To Reproduce**
Steps to reproduce the behavior are
1. Log into tutor as a student
2. Click on manage payments
3. Click Refund on a purchased course
4. Fill out the information and click submit refund
5. Notice that a 500 error is triggered and the refund is not submitted/processed 

**Expected behavior**
Users can suggest a refund and receive one successfully. 

**Screenshots**
Video:
https://drive.google.com/file/d/18XRW5bXUDR4y-F3aIFvReZ2kCmZtcg6F/view?usp=sharing

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened and linked to this issue. The automated pull request checks pass. 
  - [ ] The change has been approved by other developers.
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
- [ ] Add milestone tag
  
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies. 

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes

**Comment by nathanstitt** [comment] 2019-08-23 21:25
dupe of #567 - sorry I'd missed that one before

**Closed** 2019-08-23 21:26 UTC
Labels: bug
