### ISSUE TITLE
APUSH: Bold treatment inadvertently applied in question stems in Question Library

### ISSUE THREAD

**Issue by mwest-WWprod** [openstax/tutor#637] opened 2019-10-02 20:27 UTC
ID 18042 Nickname Ch05-N-Tecumseh-RQ04, possibly GLOBAL
Tutor APUSH
https://tutor-content.openstax.org/course/88/questions

In the exercises with the ID 18042 and the nickname "Ch05-N-Tecumseh-RQ04", we have not used bold treatment in the question stem, but bold treatment **does** appear in the output. We have seen this in other questions, and initially thought they were errors but that does not appear to be the case. We will add examples to this ticket as we come upon them.

![Bold Text_TecumsehRQ04_APUSH](https://user-images.githubusercontent.com/19212926/66079000-319c5d00-e531-11e9-8862-81a8b492fc1c.png)

**Comment by openstaxalina** [comment] 2019-10-03 23:48
@mwest-WWprod what username is creating these questions?  This will be needed to review the markup here.  (I looked at the usernames `cmsupport@openstax.org` and `WWExercises1` but neither had edit access on this question.)

**Comment by mwest-WWprod** [comment] 2019-10-04 15:17
@openstaxalina We are using the following:

Link: exercises.openstax.org/exercises

username: cmsupport@openstax.org
password: apush2018

**Comment by openstaxalina** [comment] 2019-10-04 15:35
@mwest-WWprod could you check with your teams about the account they are using?  When I login with the credentials above to inspect the markup, I see the following:

![Screen Shot 2019-10-04 at 10 35 05 AM](https://user-images.githubusercontent.com/7863733/66220449-a63add00-e692-11e9-94d0-c66f3866ddce.png)

The technical team let me know that the account that authored this question is username `jeremy_doehnert`.

**Comment by mwest-WWprod** [comment] 2019-10-04 15:54
@openstaxalina That's strange, I replied in my comment above with their confirmation - I'll look into this, they should only be using the cmsupport account.

**Comment by openstaxalina** [comment] 2019-10-10 20:16
Matt triple-confirmed that teams are only using the cmsupport@openstax.org login as indicated above.  Carly is going to check with her team about whether/how assessments ownership may be getting transferred prematurely.

**Comment by openstaxalina** [comment] 2019-10-11 17:37
We discovered that this and approximately 200 other assessments were encoded with the username `jeremy_doehnert`.  I hypothesize that this occurred because teams use this username on openstax.org to encode redirects.  Exercises.openstax.org uses the same accounts system.  So if teams are logged in as `jeremy_doehnert` to create redirects, then navigate to exercises.openstax.org, they will be logged in as `jeremy_doehnert`.  @mwest-WWprod I will provide further instructions to avoid this issue in the future.

In the meantime, we transferred all assessments that had been encoded under the username `jeremy_doehnert` to authorship by `cmsupport@openstax.org` so that account will have access to edit these assessments.

I reviewed the above assessment and confirmed there is no bolding treatment applied in the markup (screenshot below).  However, I reviewed the Question Library for chapters 1-5 and noted that **all question stems are bold.** Therefore, I believe (need @carlycurran to confirm) that the bolding is standard Tutor treatment for all components of a question stem.

@mwest-WWprod to confirm - the request is for the text in the red box above to be roman (not bold, not italics)? 

![Screen Shot 2019-10-11 at 12 30 16 PM](https://user-images.githubusercontent.com/7863733/66672262-8459d100-ec23-11e9-9c97-506d2a2c2256.png)

cc @oscryan

**Comment by mwest-WWprod** [comment] 2019-10-11 21:11
@openstaxalina That is correct - the caption, instructions ('Refer to...') and question stem should all not be bold.

**Comment by carlycurran** [comment] 2019-10-14 17:28
@openstaxalina @mwest-WWprod 

In Tutor, we apply bold treatment to all question stems ONLY in the Question Library and the assignment builder. This is to help teachers scan through questions more easily as they build assignments or review questions.

Here's an example of AP Physics Question Library. 
![Screen Shot 2019-10-14 at 12.18.36 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/c7a3b7b2-8451-4824-b23a-30ccd5b14e80)

And here's a Physics question from the student's view
![Screen Shot 2019-10-14 at 12.27.10 PM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/380aa996-ecb0-4590-8453-c26e2b21fd85)

**Comment by carlycurran** [comment] 2019-10-14 17:29
This is not a bug; it's intentional, so I'm going to close this card 

cc @openstaxalina

**Comment by mwest-WWprod** [comment] 2019-10-14 18:02
@carlycurran For content purposes, to confirm we _do_ need to remove bold treatment from the question stems, let me know if this is not possible though.

**Closed** 2019-10-14 18:03 UTC
Labels: bug, priority2-med

**Comment by carlycurran** [comment] 2019-10-14 18:06
@mwest-WWprod It is not posible to remove bold treatment from question stems in the QL or the assignment builder. The bold does not show up in student views.

**Comment by carlycurran** [comment] 2019-10-14 18:09
@mwest-WWprod @openstaxalina This is an intentional UX choice. Why would this change be necessary for content purposes?

**Comment by mwest-WWprod** [comment] 2019-10-14 18:31
@carlycurran That was my mistake, I misread your comment above initially re: the assignment builder. That is fine as is if they are not bold for students - can we add this to the shared output documentation to clarify re: the Question Library? 

https://docs.google.com/document/d/1RnIWU45JHnof3Ue2j6wa4p0RXrXjDzlRRyCGtIg-JJA/edit?usp=sharing

**Comment by carlycurran** [comment] 2019-10-14 18:41
Yup! added to the doc. Thanks.
