### ISSUE TITLE
SPARFA: investigate SPARFA taking longer than LQC to build assignments. 

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#583] opened 2019-09-03 15:51 UTC
### Description
As a Tutor user, I want my assignments on time, consistently, so that I can do my work when I'm ready.

### Acceptance Criteria
Give criteria for acceptance.

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [ ] Release is selected

1C-DESIGN
- [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] If UI changes, UX reviews and verifies on -dev or -qa
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.
  

<!-- If this story becomes an epic, delete the Checklist for Done above and uncomment this one
### Checklist for Done
1A-DEFINE
- [ ] Description is complete 
- [ ] Acceptance criteria are complete
- [ ] If UX design is needed then the UX label is added
- [ ] If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue.
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] If this issue is an epic, then Epic is selected and all child issues are linked to it.

TRACK / EPICS
- [ ] All child issues are closed.
>

**Comment by Brooke-Fail** [comment] 2019-09-19 19:59
I tested this with the same course (https://tutor-qa.openstax.org/enroll/395163/Biology-2e-Fall-2019 on QA already used student04, 05, 02, and 08 to test). LQC took abut 1 min and 10 seconds. SPARFA too about 2 mins and 5 seconds. This does seem to be an improvement from the last time I compared the times (lqc being about the same 1 min 10-30 seconds, and sparfa being about 3 minutes. Almost 3 times a long).

**Comment by carlycurran** [comment] 2019-09-19 20:10
hmm @Dantemss any thoughts? should we be trying this on prod, where we increased the SPARFA instance?

**Comment by Dantemss** [comment] 2019-09-19 20:22
Yes, prod is probably the best place to do this comparison

**Comment by Dantemss** [comment] 2019-09-19 20:23
But don't enable SPARFA on prod for this test. Once SPARFA is deployed, I can pull up the timing data from biglearn-scheduler.

**Comment by Brooke-Fail** [comment] 2019-09-19 20:44
I'll get the timing comparison on production and send the info to you. I'll still run a comparison on staging just to see if it improved from the times I got in QA. Moving to Regression.

**Comment by Brooke-Fail** [comment] 2019-09-24 19:00
Verified in Staging. The timing difference between sparfa and local query isnt that larger in staging. The biggest difference is if a hw loads immediately or when the readings do, which is less than a minute. 

<img width="518" alt="Screen Shot 2019-09-24 at 1 55 20 PM" src="https://user-images.githubusercontent.com/48449285/65541782-9291b880-ded3-11e9-9da2-41afd09566c8.png">

**Comment by Brooke-Fail** [comment] 2019-09-25 18:57
After looking at the production time, it looks like sparfa should take about a minute to load, like it does on production. Closing.

**Closed by Brooke-Fail** 2019-09-25 18:57 UTC
