### ISSUE TITLE
Figure missing in tutor vs. cnx

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#187] opened 2018-12-17 18:33 UTC
**Describe the bug**
Figure missing in tutor vs. cnx 
section 14.6 physics fig 14.22 is missing in tutor but present in cnx

https://drive.google.com/file/d/1VATYj1csKY-HZXo39j-gCNcujRV87fM6/view?usp=sharing

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by carlycurran** [comment] 2018-12-19 20:38
@brittany-johnson, can you do a little investigation into the cause of this missing image?

**Comment by brittany-johnson** [comment] 2018-12-20 15:13
@carlycurran It looks like it was just being pushed off the page because of styling! Once this PR is merged, this is what it will look like: 

![screen shot 2018-12-20 at 9 10 37 am](https://user-images.githubusercontent.com/24909007/50292672-535fa400-0437-11e9-8274-d4a0f2fda8ad.png)
![screen shot 2018-12-20 at 9 11 59 am](https://user-images.githubusercontent.com/24909007/50292673-535fa400-0437-11e9-8aa7-a9cd12f150fb.png)

**Comment by gregfitch** [comment] 2019-01-07 19:21
verified on QA

**Closed** 2019-01-17 22:11 UTC
Labels: bug, priority2-med
