### ISSUE TITLE
Run performance  tests again against small and medium AWS server instances. Review data to determine deployment parameters

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#392] opened 2019-04-30 18:33 UTC
### Description
As OpenStax, I want to understand how the validation server performs at a small size, so that we know which instance size is necessary.

### Acceptance Criteria
- We see test result data
- We can estimate which server size we need for production and what changes we need to make to the algorithm to ensure that student responses are reviewed, data is sent back to Tutor, and Tutor displays a nudge (or not) in less than 2 seconds.

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete
- ~If UX design is needed then the UX label is added~
- ~ If UX design is needed then the UX LoFi Design is completed, approved by the Product Manager, and added to the issue~
- [ ] A development approach for the code change, prototype code, or tech brief is done and added to the issue

1B-DECOMP
  - [x] The work is broken into reasonable and consistent work items
  - [ ] Estimate is updated
  - [x] Release is selected

1C-DESIGN
  - [ ] The UX HiFi Design is complete, approved by the Product Manager, and added to the issue
  - [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
  - [ ] Automated testing criteria are added to issue
  - [ ] The development approach is reviewed/updated

2A-CODE
  - [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
  - [ ] The change has been approved by other developers
  - [ ] The pull request is merged into master, and the change branch is deleted.
  - [ ] The acceptance tests are finalized
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
  - [ ] If UI changes, UX reviews and verifies on -dev or -qa
  - [ ] PDM reviews and verifies

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
  - [ ] The test plan in testrail passes.

**Comment by reedstrm** [comment] 2019-05-09 18:57
used siege load testing tool to run a variety of tests, with different synthetic and actual response texts. Used this information to determine that the server seems to be CPU bound. Requested an increased instance size, with 2 CPUs. Repeating tests confirmed doubling of performance, as seen in this figure:
![Performance scaling with CPU](https://user-images.githubusercontent.com/253212/57478771-6eee0e80-7261-11e9-8778-725720ed9668.png)

**Comment by reedstrm** [comment] 2019-05-09 19:19
Further testing with 100 exemplar responses (taken from actual student work) found that:
1. auto-spelling correct (only correct when response is not valid w/o correcting) is a big win
2. the optimum number of processes is == number of CPUs (2)
![Screenshot from 2019-05-09 14-18-22](https://user-images.githubusercontent.com/253212/57480481-7a433900-7265-11e9-846a-c7eb6eb21330.png)

**Comment by carlycurran** [comment] 2019-05-09 19:21
very cool!! loving this :)

**Comment by reedstrm** [comment] 2019-05-09 19:24
Finally, to answer the question as to scale of deployment: Analysis of Big Learn logs tells us that, at peak usage in the last 3 months, we had at most 4 simultaneous response submissions (within the same second), even though peak user sessions is around 300-400 (group per hour).
Using a single 2-CPU medium instance, we can sustain 28 simultaneous requests, at a rate of 128 requests/second
![Screenshot from 2019-05-09 13-00-03](https://user-images.githubusercontent.com/253212/57480694-10775f00-7266-11e9-9415-04f7ccd577b3.png)

**Comment by reedstrm** [comment] 2019-05-09 19:26
Therefore, recommend deploying initially on a single dual-CPU medium AWS instance.

**Comment by carlycurran** [comment] 2019-05-09 19:28
Nice. This is a really great analysis, @reedstrm . 
Devops is on board, it looks like, and single dual-CPU medium AWS instance is deployed to QA. 
What do you recommend re timeline for production?

**Comment by reedstrm** [comment] 2019-05-09 19:49
Drew and I are committed to code freeze tomorrow, for the next release. (May 22, I believe)

**Comment by reedstrm** [comment] 2019-05-09 19:50
Raw data logs, for posterity:
[response-validation-load.zip](https://github.com/openstax/tutor/files/3163717/response-validation-load.zip)

**Comment by reedstrm** [comment] 2019-05-10 18:18
Improved performance with new spellchecker (symspell):
![Screenshot from 2019-05-10 13-12-02](https://user-images.githubusercontent.com/253212/57548010-90183300-7325-11e9-8063-908b483eb616.png)

We can now handle approx. 40x our highest observed api usage rate, and still respond in 1 sec at max. We're ready for 200,000 students, right now. :-)

**Comment by Brooke-Fail** [comment] 2019-05-30 14:31
Verify in QA.

**Comment by Brooke-Fail** [comment] 2019-06-03 19:35
Verified in Staging.

**Comment by Brooke-Fail** [comment] 2019-06-05 15:45
Verified in Production.

**Closed by Brooke-Fail** 2019-06-05 15:45 UTC
Labels: story

**Comment by reedstrm** [comment] 2019-06-12 18:46
[response-validate-raw-2019-05-10.zip](https://github.com/openstax/tutor/files/3282737/response-validate-raw-2019-05-10.zip)
Raw logs  and data for last graph, above.
