### ISSUE TITLE
Don’t allow "Test Prep for AP® Courses" or "Science Practice Challenge Questions" to be selectable when creating reading/HW assignments 

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#532] opened 2019-08-05 12:50 UTC
### Description
Don’t allow "Test Prep for AP® Courses" or "Science Practice Challenge Questions" to be selectable when creating reading/HW assignments 

### Acceptance Criteria
These end-of-chapter questions appear in reference view, but are not available to assign when creating a reading assignment or when selecting HW problems.

### Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Epic Doc
URL

### Checklist for Done
1A-DEFINE
- [x] Description is complete 
- [x] Acceptance criteria are complete

1B-DECOMP
- [ ] The work is broken into reasonable and consistent work items
- [ ] Estimate is updated
- [ ] Release is selected

1C-DESIGN
- [ ] Distilled acceptance tests are added to the issue in "Given / When / Then" format
- [ ] Automated testing criteria are added to issue
- [ ] The development approach is reviewed/updated

2A-CODE
- [ ] A pull request is opened and linked to an issue. The automated pull request checks pass
- [ ] The change has been approved by other developers
- [ ] The pull request is merged into master, and the change branch is deleted.
- [ ] The acceptance tests are finalized
- [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
 
4A-UX REVIEW
- [ ] PDM reviews and verifies

5A-FUNCT VER
- [ ] All the acceptance tests for this issue pass.

5C-REGRESSION
- [ ] The test plan in testrail passes.

**Comment by nathanstitt** [comment] 2019-08-08 16:22
somewhat a dupe of https://github.com/openstax/tutor/issues/535,  was fixed in https://github.com/openstax/tutor-js/pull/2685

**Comment by Brooke-Fail** [comment] 2019-08-13 20:02
Verified in QA.

**Comment by Brooke-Fail** [comment] 2019-08-15 20:25
Test pre for AP is selectable:
https://tutor-staging.openstax.org/course/5716/t/month/2019-08-15
bf22+103@rice.du

**Comment by Brooke-Fail** [comment] 2019-08-20 14:21
This is fine as is for this release. The card mentioned in the comment above will be fixed in another release.

**Comment by Brooke-Fail** [comment] 2019-08-21 17:18
Earlier comments are verified in Production.

**Closed by Brooke-Fail** 2019-08-21 17:18 UTC
Labels: change, priority1-high
