### ISSUE TITLE
Certain text in Sec 4.7 Physics is having a different font - Baking issue may be

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#272] opened 2019-02-07 22:48 UTC
### Description
Certain text in Sec 4.7 Physics is having a different font. See Step 2 in section 4.7 below the subheading "Integrating Concepts: Newton’s Laws of Motion and Kinematics"

https://tutor-staging.openstax.org/book/276/section/4.7 . mn45+34234@rice.edu

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**
![Screen Shot 2019-02-07 at 4.44.29 PM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/559b657c-fb97-4a91-be46-e1d737071ebf)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by nathanstitt** [comment] 2019-05-07 18:52
This was probably a content issue. I no longer see it occurring in the latest (22.7) version of AP Physics

![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/15e93a7a-c7c5-4e45-9164-2eb2bea28e8c)

**Comment by CaptainXep** [comment] 2019-05-14 18:51
Font changing still appears in latest version of tutor:
![Screen Shot 2019-05-14 at 1.49.31 PM.png](https://images.zenhubusercontent.com/5b94256dee716b0ad3ad2c44/56d9e945-04f8-4693-a10e-7a1f48ea80ac)

Link:
https://tutor-qa.openstax.org/book/2559/section/4.7

**Comment by nathanstitt** [comment] 2019-05-14 20:28
The latest content update seems to have fixed this.  On QA as teacher01 in a new course https://tutor-qa.openstax.org/book/2561/section/4.8  I see:

![image.png](https://images.zenhubusercontent.com/5b6c72f28ef805470660da46/d391da4f-d7b8-446e-860f-50d7b917d24b)

**Comment by CaptainXep** [comment] 2019-05-15 14:47
Verified in QA. The College Physics book still has different fonts but is confirmed to be a content issue that the content team is aware of and has fixed.

**Comment by carlycurran** [comment] 2019-05-21 18:30
content looks good - we're closing this card because when we import the next version of College Physics, this will be fixed.

**Closed by carlycurran** 2019-05-21 18:30 UTC
Labels: bug, priority3-low
