### ISSUE TITLE
APUSH: Embedded videos fall outside of full column container

### ISSUE THREAD

**Issue by mwest-WWprod** [openstax/tutor#549] opened 2019-08-19 15:23 UTC
GLOBAL
Tutor APUSH
https://tutor-content.openstax.org/book/88

Videos fall outside of full-column containers in 'Browse the Book' view. Should extend to the edge of the full-width column as with text content.

![videos_container](https://user-images.githubusercontent.com/19212926/63277467-6307e480-c273-11e9-9168-82a3a7fdbb42.JPG)

**Comment by carlycurran** [comment] 2019-09-03 16:23
@mwest-WWprod  The video does fall outside of the note, but all of our videos go full-width across the card container. 

This expected behavior.

**Comment by mwest-WWprod** [comment] 2019-09-18 17:21
@carlycurran please see attached screenshot, which provides better context - the video falls outside of the main narrative text margins.
![videos_container 2](https://user-images.githubusercontent.com/19212926/65170718-3c2a0300-da17-11e9-8fd3-3ccec8b7be18.JPG)

**Comment by oscryan** [comment] 2019-09-25 17:57
All embedded video has width="660" height="371.4" specified because otherwise it defaults to a tiny view size with the wrong proportions. WiseWire can change this at discretion, but this is the idea size to watch a  16:9 youtube video.

**Comment by openstaxalina** [comment] 2019-10-07 20:27
Discussed on 10/3 call:

Video is displaying per standard Tutor behavior (it extends to the end of the "card" or the white background).  Changes would be low priority. WW to communicate to BRI that what was seen in prototype is no longer viable.

@carlycurran okay to close?

**Comment by carlycurran** [comment] 2019-10-07 20:29
yup! closing

**Closed by carlycurran** 2019-10-07 20:29 UTC
Labels: change, priority2-med
