### ISSUE TITLE
Masses & springs Sims in 7.4 physics is not displaying correctly in HW assignment (part of MPQ)

### ISSUE THREAD

**Issue by Malar-Natarajan** [openstax/tutor#274] opened 2019-02-11 17:35 UTC
### Description
Masses & springs Sims in 7.4 physics is not displaying correctly in HW assignment (part of MPQ)
https://tutor-staging.openstax.org/course/4090/task/1404268/step/3
mn45+76687@rice.edu

The user cannot play around with the colored weights since its behind the frame. Happens in safari, chrome

**To Reproduce**
Steps to reproduce the behavior are

**Expected behavior**

**Screenshots**
![Screen Shot 2019-02-11 at 11.12.01 AM.png](https://images.zenhubusercontent.com/5b23e2cc835fb47f522b81ba/6bf2b9a4-b4e4-4ae9-bd5a-73c8d2e01208)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### Acceptance Tests
Additional acceptance tests that are required by this bug fix.

**title**: template  
**categories**: Interactive Component, Navigation, TOC, Math, Book Content, Other
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

### Checklist for Done
2-CODE
  - [ ] A pull request is opened, the automated pull request checks pass, and the change has been approved by other developers.
  - [ ] If there are new acceptance tests, they are finalized in "Given / When / Then" format.
  - [ ] Regression test categories are identified on the issue. Categories should be referenced if any changes might affect them, even if the intended functionality is unchanged.
  
4A-UX REVIEW
  - [ ] The pull request is merged into master, and the change branch is deleted.

5A-FUNCT VER
  - [ ] All the acceptance tests for this issue have passed.
 
5C-REGRESSION
  - [ ] The test plan in testrail passes
  - [ ] Blessing from Product Manager that the release is good to go.

5D-READY TO BE DEPLOYED
  - [ ] Production is updated and verified.
  - [ ] All issues in the release are closed.

**Comment by Brooke-Fail** [comment] 2019-03-19 21:06
@nathanstitt 

The issue is still occurring and there are a few more issues I found with the Masses and Springs simulation.

1. The original issue, not being able to play around with the colored weights. If one of the grey weights is placed behind the frame, the user is not able to move it either. 
2. If the Stopwatch is checked, the Reset All button gets hidden. The user is unable to reset the simulation to its original state unless they refresh the whole page.
3. There is no way to close or minimize the Stopwatch once it is opened.
4. The + zoom button does not go to the next correct interval if the number is below 1x. If the zoom is at 0.5x and the + button is clicked, it goes to 2x instead of the next interval of 1x.
5. There appears to be a pause button that overlaps the Normal selection. If the use tried to click this, the Normal button is selected instead. The pause button can not be click even when the simulation is playing an animation. 

Video of issues: https://drive.google.com/open?id=19hegc4dsiZwu83OrGnbku5IyysUiXRiF

User: bf22+01@rice.edu
Course Number: 2480
Link issue occurs on: https://tutor-qa.openstax.org/course/2480/task/376764
Tested in: Tutor QA

Steps to Reproduce:
1. Log on to Tutor
2. Click on College Physics
3. Click the mass&spring assignment (this should be under This Week, if not try All Past Work)
4. In the Masses and Springs simulation, try to move the colored weights. Check the other issues mentioned as well.

**Comment by Brooke-Fail** [comment] 2019-07-22 20:32
Verified in QA.

**Comment by Brooke-Fail** [comment] 2019-08-06 16:14
Verified in Staging. This exercise is currently turned off in the Tutor admin setting in Production. I don't want to risk messing up any courses or assignments by turning it on in production to verify. Closing for now, based on the previous testing, this is verified fixed.

**Closed by Brooke-Fail** 2019-08-06 16:14 UTC
Labels: bug, priority1-high
