### ISSUE TITLE
Note icon not showing up for some highlights

### ISSUE THREAD

**Issue by carlycurran** [openstax/tutor#164] opened 2018-12-11 15:51 UTC
**Describe the bug**
Note icon is showing up for some notes, but not for others. 
Tutor-QA
Student01
Physics 

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screen Shot 2018-12-11 at 9.46.28 AM.png](https://images.zenhubusercontent.com/5bad043a15508f6a7f088856/1d293987-4573-4e3d-974d-4c2ee8a409a0)

**Comment by nathanstitt** [comment] 2018-12-18 17:04
fixed in https://github.com/openstax/tutor-js/pull/2454

**Comment by nathanstitt** [comment] 2018-12-20 02:40
fixed by: https://github.com/openstax/tutor-js/pull/2454

**Comment by gregfitch** [comment] 2019-01-09 15:36
can't reproduce; accepting

**Closed** 2019-01-17 22:10 UTC
Labels: bug
